//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.images = new HashSet<images>();
            this.product_label = new HashSet<product_label>();
            this.sizes_product = new HashSet<sizes_product>();
        }
    
        public long idProduct { get; set; }
        public string nameProduct { get; set; }
        public string description { get; set; }
        public string extendDescription { get; set; }
        public long idBrand { get; set; }
        public long idCategory { get; set; }
        public long idSubCategory { get; set; }
        public string keyProduct { get; set; }
        public long stock { get; set; }
        public decimal discount { get; set; }
        public decimal salePrice { get; set; }
        public decimal wholesalePrice { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public int status { get; set; }
        public long limitWholeSalePrice { get; set; }
        public string Image_link { get; set; }
    
        public virtual brands brands { get; set; }
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<images> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_label> product_label { get; set; }
        public virtual subcategories subcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sizes_product> sizes_product { get; set; }
    }
}
